module.exports = {
  ACTION_TYPE: {
    TOGGLE_FAV_FILM: "tff",
    SHOW_CINEMAS: "sc",
    SHOW_CINEMAS_MAP: "scm",
    SHOW_FILMS: "sf",

    ADD_DISH_TO_CART: "ADD_DISH_TO_CART",
    COURIER_DELIVERY: "COURIER_DELIVERY",
    PICKUP_DELIVERY: "PICKUP_DELIVERY",
    SEND_ORDER_TO_OPERATOR: "SEND_ORDER_TO_OPERATOR",
    CLEAN_CART: "CLEAN_CART",
    SHOW_LOCATION_ON_MAP: "SHOW_LOCATION_ON_MAP",
    GET_ITEM_DATA: "GET_ITEM_DATA",
  },
};
